# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cf8ea71f3666db0f1c746639d76eec4070fd236e9f4e80478fe9551eb4d272130e49d14dcf698782478e0aa74d15af4fa65720cb9c06b682589381559bf1475

test:
  secret_key_base: 7fb5bacff108359b150fddb3febce35943533260adb304c57f2b31a9a2f59fafd4872da680b0c86d872064e529338bf6d7a2e2b4c173f744c2a6c0559b4eb72a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
